import { Component, OnInit, signal, computed, ViewChild, ElementRef, AfterViewInit, effect } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import Highcharts from 'highcharts';
import Highcharts3D from 'highcharts/highcharts-3d';
const highcharts3d = Highcharts3D as unknown as { default?: (highcharts: typeof Highcharts) => void } | ((highcharts: typeof Highcharts) => void);
if (typeof highcharts3d === 'function') highcharts3d(Highcharts);
else highcharts3d.default?.(Highcharts);
type Expense={id?:number;description:string;category:string;amount:number;date:string};
@Component({selector:'app-root',imports:[FormsModule,CommonModule],templateUrl:'./app.html',styleUrl:'./app.css'})
export class App implements OnInit, AfterViewInit{
 private highcharts=Highcharts; private chart?: Highcharts.Chart;
 loading=signal(true);
 @ViewChild('donutChart') donutChart?: ElementRef<HTMLDivElement>; private chartReady=false;
 expenses=signal<Expense[]>([]);selectedMonth=signal(new Date().toISOString().slice(0,7));search=signal('');form:Expense={description:'',category:'Alimentación',amount:0,date:new Date().toISOString().slice(0,10)};categories=['Alimentación','Vivienda','Transporte','Ocio','Salud','Suscripciones','Otros'];filtered=computed(()=>this.expenses().filter(e=>e.date.startsWith(this.selectedMonth())&&e.description.toLowerCase().includes(this.search().toLowerCase())));total=computed(()=>this.filtered().reduce((s,e)=>s+e.amount,0));average=computed(()=>this.filtered().length?this.total()/this.filtered().length:0);monthLabel=computed(()=>new Intl.DateTimeFormat('es-ES',{month:'long',year:'numeric'}).format(new Date(this.selectedMonth()+'-02')));
 constructor(){effect(()=>{this.filtered();if(this.chartReady)setTimeout(()=>this.renderChart())})} async ngOnInit(){this.expenses.set(await this.all())} ngAfterViewInit(){this.chartReady=true;this.renderChart()} async addExpense(){if(!this.form.description||this.form.amount<=0)return;await this.save({...this.form,amount:+this.form.amount});this.form={description:'',category:'Alimentación',amount:0,date:new Date().toISOString().slice(0,10)}} async removeExpense(id?:number){if(id===undefined)return;await this.del(id);this.expenses.set(this.expenses().filter(e=>e.id!==id))} previousMonth(){let d=new Date(this.selectedMonth()+'-02');d.setMonth(d.getMonth()-1);this.selectedMonth.set(d.toISOString().slice(0,7))} nextMonth(){let d=new Date(this.selectedMonth()+'-02');d.setMonth(d.getMonth()+1);this.selectedMonth.set(d.toISOString().slice(0,7))}
 private renderChart(){if(!this.donutChart)return;const grouped=new Map<string,number>();for(const e of this.filtered())grouped.set(e.category,(grouped.get(e.category)||0)+e.amount);this.chart?.destroy();this.chart=Highcharts.chart(this.donutChart.nativeElement,{chart:{type:'pie',backgroundColor:'transparent',options3d:{enabled:true,alpha:55,beta:0,depth:35},animation:{duration:650}},title:{text:`<span style="font-size:24px;font-weight:700;color:#f5fbf8">${this.total().toFixed(2)} €</span> <span style="font-size:11px;color:#a9beb6">TOTAL DEL MES</span>`,useHTML:true,align:'left',verticalAlign:'top',x:18,y:18},credits:{enabled:false},tooltip:{pointFormat:'<b>{point.y:.2f} €</b> · <b>{point.percentage:.1f}%</b>'},plotOptions:{pie:{innerSize:'62%',depth:35,dataLabels:{enabled:true,format:'{point.name}<br><b>{point.percentage:.0f}%</b>',distance:24,connectorWidth:1,connectorColor:'#70cdb0',style:{fontSize:'11px',fontWeight:'600',color:'#f5fbf8',textOutline:'none'}},showInLegend:false,animation:{duration:650}}},responsive:{rules:[{condition:{maxWidth:520},chartOptions:{title:{x:8,y:8},plotOptions:{pie:{dataLabels:{distance:14,style:{fontSize:'10px'}}}}}}]},series:[{type:'pie',name:'Gastos',data:[...grouped.entries()].map(([name,y])=>({name,y}))}]});}
 exportJson(){let b=new Blob([JSON.stringify(this.expenses(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='gastos.json';a.click()} async importJson(ev:Event){let i=ev.target as HTMLInputElement,f=i.files?.[0];if(!f)return;try{let d=JSON.parse(await f.text()) as Expense[];for(let e of d)await this.save({description:e.description,category:e.category,amount:+e.amount,date:e.date});this.expenses.set(await this.all())}catch{alert('Archivo JSON inválido')}i.value=''}
 private db(){return new Promise<IDBDatabase>((ok,no)=>{let r=indexedDB.open('gastos-mensuales',1);r.onupgradeneeded=()=>r.result.createObjectStore('expenses',{keyPath:'id',autoIncrement:true});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})} private async all(){let d=await this.db();return new Promise<Expense[]>((ok,no)=>{let r=d.transaction('expenses').objectStore('expenses').getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})} private async save(e:Expense){let d=await this.db();return new Promise<void>((ok,no)=>{let r=d.transaction('expenses','readwrite').objectStore('expenses').add(e);r.onsuccess=()=>{this.expenses.update(items=>[...items,{...e,id:r.result as number}]);ok()};r.onerror=()=>no(r.error)})} private async del(id:number){let d=await this.db();return new Promise<void>((ok,no)=>{let r=d.transaction('expenses','readwrite').objectStore('expenses').delete(id);r.onsuccess=()=>ok();r.onerror=()=>no(r.error)})}}
