import { Component,OnInit,signal,computed,ViewChild,ElementRef,AfterViewInit,effect } from '@angular/core';
import { FormsModule } from '@angular/forms'; import { CommonModule } from '@angular/common'; import Highcharts from 'highcharts'; import Highcharts3D from 'highcharts/highcharts-3d';
const h3=Highcharts3D as unknown as {default?:Function}|Function;if(typeof h3==='function')h3(Highcharts);else h3.default?.(Highcharts);
type Expense={id?:number;description:string;category:string;amount:number;date:string};
@Component({selector:'app-root',imports:[FormsModule,CommonModule],templateUrl:'./app.html',styleUrl:'./app.css'})
export class App implements OnInit,AfterViewInit{
 @ViewChild('donutChart') donutChart?:ElementRef<HTMLDivElement>;@ViewChild('budgetChart') budgetChart?:ElementRef<HTMLDivElement>;private chart?:Highcharts.Chart;private budget?:Highcharts.Chart;chartReady=false;salaryInput=signal(0);incomeEntries=signal<number[]>([]);
 expenses=signal<Expense[]>([]);selectedMonth=signal(new Date().toISOString().slice(0,7));salary=signal(0);search=signal('');form:Expense={description:'',category:'Alimentación',amount:0,date:new Date().toISOString().slice(0,10)};categories=['Alimentación','Vivienda','Transporte','Ocio','Salud','Suscripciones','Otros'];filtered=computed(()=>this.expenses().filter(e=>e.date.startsWith(this.selectedMonth())&&e.description.toLowerCase().includes(this.search().toLowerCase())));total=computed(()=>this.filtered().reduce((s,e)=>s+e.amount,0));average=computed(()=>this.filtered().length?this.total()/this.filtered().length:0);remaining=computed(()=>Math.max(0,this.salary()-this.total()));monthLabel=computed(()=>new Intl.DateTimeFormat('es-ES',{month:'long',year:'numeric'}).format(new Date(this.selectedMonth()+'-02')));
 constructor(){effect(()=>{this.filtered();this.salary();if(this.chartReady)setTimeout(()=>{this.renderChart();this.renderBudget()})})}
 async ngOnInit(){this.loadSalary();this.expenses.set(await this.all())}ngAfterViewInit(){this.chartReady=true;this.renderChart();this.renderBudget()}
 loadSalary(){const key='salary-entries-'+this.selectedMonth();let entries=JSON.parse(localStorage.getItem(key)||'[]') as number[];if(!entries.length){const legacy=Number(localStorage.getItem('salary-'+this.selectedMonth()))||0;if(legacy)entries=[legacy]}this.incomeEntries.set(entries);this.salary.set(entries.reduce((s,e)=>s+e,0))}addSalary(){const amount=Number(this.salaryInput());if(amount<=0)return;const entries=[...this.incomeEntries(),amount];this.incomeEntries.set(entries);this.salary.set(entries.reduce((s,e)=>s+e,0));localStorage.setItem('salary-entries-'+this.selectedMonth(),JSON.stringify(entries));this.salaryInput.set(0)}removeSalary(index:number){const entries=this.incomeEntries().filter((_,i)=>i!==index);this.incomeEntries.set(entries);this.salary.set(entries.reduce((s,e)=>s+e,0));localStorage.setItem('salary-entries-'+this.selectedMonth(),JSON.stringify(entries))}previousMonth(){let d=new Date(this.selectedMonth()+'-02');d.setMonth(d.getMonth()-1);this.selectedMonth.set(d.toISOString().slice(0,7));this.loadSalary()}nextMonth(){let d=new Date(this.selectedMonth()+'-02');d.setMonth(d.getMonth()+1);this.selectedMonth.set(d.toISOString().slice(0,7));this.loadSalary()}
 async addExpense(){if(!this.form.description||this.form.amount<=0)return;await this.save({...this.form,amount:+this.form.amount});this.form={description:'',category:'Alimentación',amount:0,date:new Date().toISOString().slice(0,10)}}async removeExpense(id?:number){if(id===undefined)return;await this.del(id);this.expenses.set(this.expenses().filter(e=>e.id!==id))}
 private renderChart(){if(!this.donutChart)return;const grouped=new Map<string,number>();for(const e of this.filtered())grouped.set(e.category,(grouped.get(e.category)||0)+e.amount);this.chart?.destroy();this.chart=Highcharts.chart(this.donutChart.nativeElement,{chart:{type:'pie',backgroundColor:'transparent',options3d:{enabled:true,alpha:55,beta:0,depth:35}},title:{text:`<b style="color:#f5fbf8">${this.total().toFixed(2)} €</b> <span style="font-size:11px;color:#a9beb6">TOTAL DEL MES</span>`,useHTML:true,align:'left',verticalAlign:'top',x:18,y:18},credits:{enabled:false},plotOptions:{pie:{innerSize:'62%',depth:35,dataLabels:{enabled:true,format:'{point.name}<br><b>{point.percentage:.0f}%</b>',distance:24,style:{color:'#f5fbf8',textOutline:'none'}}}},series:[{type:'pie',name:'Gastos',data:[...grouped.entries()].map(([name,y])=>({name,y}))}]})}
 private renderBudget(){if(!this.budgetChart)return;const spent=Math.min(this.total(),this.salary()),available=Math.max(0,this.salary()-this.total());this.budget?.destroy();this.budget=Highcharts.chart(this.budgetChart.nativeElement,{chart:{type:'pie',backgroundColor:'transparent',options3d:{enabled:true,alpha:55,beta:0,depth:35},animation:{duration:650}},title:{text:`<b style="font-size:24px;color:#f5fbf8">${available.toFixed(2)} €</b> <span style="font-size:11px;color:#a9beb6">DISPONIBLE</span>`,useHTML:true,align:'left',verticalAlign:'top',x:18,y:18},credits:{enabled:false},tooltip:{pointFormat:'<b>{point.y:.2f} €</b>'},plotOptions:{pie:{innerSize:'68%',depth:35,dataLabels:{enabled:true,format:'{point.name}<br><b>{point.y:.2f} €</b>',distance:24,connectorWidth:1,connectorColor:'#70cdb0',style:{color:'#f5fbf8',textOutline:'none'}},animation:{duration:650}}},series:[{type:'pie',name:'Presupuesto',data:[{name:'Gastado',y:spent,color:'#8b72ff'},{name:'Disponible',y:available,color:'#31405f'}]}]})}
 exportJson(){const b=new Blob([JSON.stringify(this.expenses(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='gastos.json';a.click()}async importJson(ev:Event){const i=ev.target as HTMLInputElement,f=i.files?.[0];if(!f)return;try{const d=JSON.parse(await f.text()) as Expense[];for(const e of d)await this.save({description:e.description,category:e.category,amount:+e.amount,date:e.date});this.expenses.set(await this.all())}catch{alert('Archivo JSON inválido')}i.value=''}
 private db(){return new Promise<IDBDatabase>((ok,no)=>{const r=indexedDB.open('gastos-mensuales',1);r.onupgradeneeded=()=>r.result.createObjectStore('expenses',{keyPath:'id',autoIncrement:true});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}private async all(){const d=await this.db();return new Promise<Expense[]>((ok,no)=>{const r=d.transaction('expenses').objectStore('expenses').getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}private async save(e:Expense){const d=await this.db();return new Promise<void>((ok,no)=>{const r=d.transaction('expenses','readwrite').objectStore('expenses').add(e);r.onsuccess=()=>{this.expenses.update(items=>[...items,{...e,id:r.result as number}]);ok()};r.onerror=()=>no(r.error)})}private async del(id:number){const d=await this.db();return new Promise<void>((ok,no)=>{const r=d.transaction('expenses','readwrite').objectStore('expenses').delete(id);r.onsuccess=()=>ok();r.onerror=()=>no(r.error)})}}
